### ISSUE TITLE
Formatting error in the user starred papers page | GSSoC '23

### ISSUE THREAD

**Issue by AmoghCreator** [nawed2611/paperbrain#12]
![Screenshot from 2023-05-21 06-45-32](https://github.com/nawed2611/paperbrain/assets/109089135/cd1e0ac6-574d-477b-9e81-5b597d1d51b1)

The following is an easy fix, please assign it to me as a contributor for GSSOC '23

**Comment by SaadAnzar** [comment]
@AmoghCreator we are going to show all the starred papers here, it is a work in progress.
