### ISSUE TITLE
Re-rendering of divs in Upload Paper page | GSSoC '23

### ISSUE THREAD

**Issue by AmoghCreator** [nawed2611/paperbrain#13]
![Screenshot from 2023-05-21 06-48-06](https://github.com/nawed2611/paperbrain/assets/109089135/9344c701-a50a-403b-9690-5ff6decb3644)

This seems to be a re rendering issue, it could also be that there are multiple entries with same meta data

**Comment by i-m-karanagarwal** [comment]
Hy @AmoghCreator  Kindly assign this issue to me, I want to work on it for GGSOC' 23.

**Comment by nawed2611** [comment]
Yeah! this page is in progress!
