### ISSUE TITLE
Favicon Addition 

### ISSUE THREAD

**Issue by Shyam1128** [nawed2611/paperbrain#16]
I think the favicon of your website doesn't match with the website theme. I can add some good favicon icon to your website which is relevant and also attractive.
So @nawed2611 please consider me for this issue/task under GSSOC'23.
Thanking You

**Comment by nawed2611** [comment]
Sure! go ahead

**Comment by Shyam1128** [comment]
hey @nawed2611 thnx for assigning me this i will do it today asap. Thank you

**Comment by oshinsaraf** [comment]
Can this issue be assigned to me?

**Comment by SaadAnzar** [comment]
@oshinsaraf sure go ahead
