### ISSUE TITLE
User Profile Div needs to be centered in responsive layout

### ISSUE THREAD

**Issue by AmoghCreator** [nawed2611/paperbrain#21]
![Screenshot from 2023-05-21 18-30-19](https://github.com/nawed2611/paperbrain/assets/109089135/ae12770b-00ae-4302-84be-d479bbf466d8)

As show above, relative to the red box the user-profile div is more aligned towards right, centering it will give it a better aesthetic.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by 1sh22** [comment]
Kindly assign this issue to me so that I can start working on it.

**Comment by SaadAnzar** [comment]
We have changed our UI.
