### ISSUE TITLE
Misalignment and lack of responsive behaviour in home page | GSSoC '23

### ISSUE THREAD

**Issue by AmoghCreator** [nawed2611/paperbrain#22]
@nawed2611 , The home page is skewed and misaligned in the responsive view, the following can be fixed by adding responsive properties to the elements, I woud be willing to fix it.
![Screenshot from 2023-05-21 18-41-57](https://github.com/nawed2611/paperbrain/assets/109089135/f7483fad-d6e9-4e64-86ae-d06b23798b81)

**Comment by Usaid-Bin-Rehan** [comment]
I as GSSOC'23 contributor can fix the responsiveness issue.

**Comment by sirajlekhak** [comment]
I am eager to contribute as a valuable team member and demonstrate my skills in GSSoC'23. If you would kindly assign me an issue, I would be delighted to work on it and showcase my abilities effectively within the program.

**Comment by AmoghCreator** [comment]
Hi @nawed2611 ,
The Pull Request has been created :- https://github.com/nawed2611/paperbrain/pull/25
