### ISSUE TITLE
Misconfiguration of Auth Page with Localhost. {GSSoC '23}

### ISSUE THREAD

**Issue by GVishnudhasan** [nawed2611/paperbrain#29]
## Detailed Description:
I would like to report a misconfiguration issue regarding the authentication page when attempting to get started. Currently, the auth page is misconfigured with the localhost page, preventing the proper functioning of the authentication process.

## Context:
The misconfiguration of the auth page with the localhost page hinders users from successfully starting their authentication journey. This issue affects the initial setup and usability of the application, leading to frustration and inconvenience.

This change is important to me as it is crucial to provide a seamless onboarding experience for users, allowing them to authenticate without any obstacles. By addressing this misconfiguration, we can ensure that users can smoothly proceed with the authentication process on the localhost page.

## Possible Solution:

1.  Review the configuration settings of the authentication page to identify the source of misconfiguration.
2. Verify that the correct redirect URLs and callback URLs are specified for the localhost environment.
3. Update the auth page configuration to match the appropriate localhost URL, ensuring compatibility with the application's backend.
4. Test the authentication process on the localhost page to confirm that the misconfiguration has been resolved.

## Additional Information:

I think this is a serious issue. Please assign this task to me under GSSoC '23 so that we could fix it ASAP.

**Comment by nawed2611** [comment]
Sure! would love to see the changes!

**Comment by GVishnudhasan** [comment]
Hi @nawed2611 , May I know the deployment link of the backend server? So that I can replace the localhost URL with the original backend server URL.

**Comment by Urmi-Jana** [comment]
Hi, @GVishnudhasan @nawed2611  has there been any progress on this issue? I still haven't been able to log in through local host and access the dev environment yet.

**Comment by GVishnudhasan** [comment]
@Urmi-Jana ,
The reason of no progress is that I haven't gotten updated regarding the deployment link of the backend URL.
