### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [nawed2611/paperbrain#32]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@nawed2611 Could you please assign this issue to me under GSSOC 23
Thank you!

**Comment by nawed2611** [comment]
Sure!

**Comment by shanvijha30** [comment]
@nawed2611 Could you please add GSSoC 23 label to this issue.

**Comment by shanvijha30** [comment]
@nawed2611 Added PR [#65](https://github.com/nawed2611/paperbrain/pull/65)
Please review it.
