### ISSUE TITLE
adding tech stack shields

### ISSUE THREAD

**Issue by mridulsaggi** [nawed2611/paperbrain#44]
i would like to add tech stack badges and shields in readme . it makes the readme look more pretty and give better information about the technologies used.
please assign me this issue as gssoc contribution
example:
![image](https://github.com/nawed2611/paperbrain/assets/91930535/d0038159-fa96-4e4d-b599-2304cb1ee7a4)

**Comment by SaadAnzar** [comment]
@mridulsaggi go ahead
