### ISSUE TITLE
Home Page is lacking responsiveness in mobile devices.

### ISSUE THREAD

**Issue by AmoghCreator** [nawed2611/paperbrain#51]
### Description

The current home page is misaligned and not properly oriented for mobile devices 

### Screenshots

![image](https://github.com/nawed2611/paperbrain/assets/109089135/301db539-8543-4d0e-868e-be67df937b66)

**Comment by AmoghCreator** [comment]
@nawed2611 Please Review, https://github.com/nawed2611/paperbrain/pull/50

**Comment by SaadAnzar** [comment]
Reviewed
