### ISSUE TITLE
📝 [DOCS]: REMOVE MANUALLY UPDATED OLD CONTRIBUTERS TABLE

### ISSUE THREAD

**Issue by 0xabdulkhalid** [nawed2611/paperbrain#66]
### Description

- This issue is about removing the old contributors table, because since it's not automatically updated and the table is also not properly structured so that the part looks worse and creates a bad impression on the `readme` file
- There is already a contributors graph on the below of `readme` which generates dynamic images for the contributors so we don't want to the old manually updated contributors table

### Screenshots

![Screenshot 2023-05-31 at 20-17-58 nawed2611_paperbrain Exploring research papers has never been easier!](https://github.com/nawed2611/paperbrain/assets/92252895/6bb2bd95-210d-4c68-bf24-e87ee8465620)

### Code of Conduct

- [X] I have checked the existing issues
- [X] I agree to follow this project's Code of Conduct
- [X] I am willing to work on this issue
- [X] I am a GSSoC'23 contributor

**Comment by SaadAnzar** [comment]
@0xabdulkhalid It is resolved now! Thanks  for your suggestion btw.
