### ISSUE TITLE
[FEATURE] Add greeting Bot

### ISSUE THREAD

**Issue by k-deepak04** [nawed2611/paperbrain#68]
### Description

"By adding a greeting bot that acknowledges and appreciates pull requests, we can create a positive and motivating environment for contributors."
"The greeting bot's personalized message will make contributors feel valued and encourage them to continue their great work."
"Having a greeting bot in place ensures that contributors receive immediate recognition and assurance that their contributions are being reviewed and appreciated."

### Screenshots

![image](https://github.com/nawed2611/paperbrain/assets/96341431/2e1d7e5e-dc16-46b9-a3db-2de33c98edf9)

### Additional information

Assign me this issue under GSSOC'23

**Comment by SaadAnzar** [comment]
@k-deepak04 ok go ahead

**Comment by k-deepak04** [comment]
#74 added
@SaadAnzar PR added
