### ISSUE TITLE
[FEATURE] Close old issue bot

### ISSUE THREAD

**Issue by k-deepak04** [nawed2611/paperbrain#69]
### Description

"By incorporating a bot that automatically closes old and inactive issues, we can ensure better issue management and keep the project organized."
"The bot's ability to identify and close outdated issues will streamline the issue tracking process, allowing the project team to focus on active and relevant tasks."
"Implementing an automated closing bot will help maintain a clean and up-to-date issue tracker, improving overall project efficiency and ensuring that active issues receive proper attention."

### Additional information

Please assign me this under GSSOC'23
And also tell me after how many days a issue should automatically be closed :)
like an issue which is not active for more than a month can be closed

**Comment by k-deepak04** [comment]
@SaadAnzar shall i start working on this?

**Comment by SaadAnzar** [comment]
@k-deepak04 i don't think we need this as we do not have much rush right now. so we can manually handle it. maybe in future.

**Comment by k-deepak04** [comment]
No worries :)
