### ISSUE TITLE
[FEATURE] Add depandabot

### ISSUE THREAD

**Issue by k-deepak04** [nawed2611/paperbrain#70]
### Description

"Integrating Dependabot into our open-source project will automate dependency updates, ensuring we stay up-to-date with the latest security patches and feature enhancements."
"By leveraging Dependabot's automated pull requests for dependency updates, we can reduce the burden on maintainers and foster a more secure and stable codebase."
"Adding Dependabot as a dependency management tool will demonstrate our commitment to maintaining a healthy ecosystem, allowing contributors to focus on higher-value tasks while keeping our project dependencies secure and reliable."

### Screenshots

![image](https://github.com/nawed2611/paperbrain/assets/96341431/ad98891e-e2a2-4e51-b42a-dccfa83547e0)

### Additional information

Please assign me this under GSSOC'23

**Comment by SaadAnzar** [comment]
@k-deepak04 go ahead

**Comment by k-deepak04** [comment]
i will add a PR shortly
