### ISSUE TITLE
[DOCS] changing the code snippet in the readme.md file

### ISSUE THREAD

**Issue by barkhaaroraa** [nawed2611/paperbrain#86]
### Description

so there's a difference in the formats of the same code snippet. I'd like to change the "git clone https://github.com/nawed2611/paperbrain.git" to  "git clone https://github.com/<your_github_username>/paperbrain.git" so that all of the code snippets are in the same format and there isn't any confusion while forking the repo.

### Screenshots

<img width="370" alt="image" src="https://github.com/nawed2611/paperbrain/assets/115429121/6da88de2-be5d-4ed3-9c40-e3ef40bfc508">
<img width="648" alt="image" src="https://github.com/nawed2611/paperbrain/assets/115429121/d25f1b6a-2ee6-4d22-8097-804dbc3ce8b6">

**Comment by barkhaaroraa** [comment]
Hi I'm a GSSoC'23 contributor please assign this issue to me

**Comment by SaadAnzar** [comment]
@barkhaaroraa ok
