### ISSUE TITLE
[FEATURE] Hover effect on icon on landing page

### ISSUE THREAD

**Issue by ManishaSwain8** [nawed2611/paperbrain#88]
### Description

Adding a little hover effect on icons in landing page will make sense.
If this change req. do assign under GSSOC 2023.

### Screenshots

https://github.com/nawed2611/paperbrain/assets/96622693/70edd4f3-c30f-4ce8-9fde-139a72b63895

**Comment by SaadAnzar** [comment]
@ManishaSwain8 go ahead
